"""
Integration tests for the invite-only channel flow.

Covers: invite token generation/verification, full invite → join → member list
flow, expired tokens, and member list versioning/tiebreak rules.
"""

import time
import struct
from unittest.mock import patch

import pytest

from tests.helpers import (
    wait_for,
    wait_for_member,
)
from trenchchat.core.invite import (
    _signed_payload,
    _verify,
)


class TestInviteTokens:
    def test_generate_and_verify_token(self, peer_factory):
        """
        A token generated by Alice for Bob is verifiable using Alice's public key.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("token-test", "", "invite")

        token, expiry = alice.invite_mgr.generate_invite_token(
            ch_hash, bob.identity.hash, ttl=3600
        )

        assert isinstance(token, bytes)
        assert expiry > time.time()

        payload = (bob.identity.hash
                   + bytes.fromhex(ch_hash)
                   + struct.pack(">d", expiry))
        assert _verify(alice.identity.rns_identity, payload, token)

    def test_expired_token_rejected(self, peer_factory):
        """
        A token with TTL=-1 (already expired) is rejected when processing
        a join request.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("expire-test", "", "invite")

        token, expiry = alice.invite_mgr.generate_invite_token(
            ch_hash, bob.identity.hash, ttl=-1
        )

        fields = {
            0x10: "join_request",
            0x01: bytes.fromhex(ch_hash),
            0x11: token,
            0x12: bob.identity.hash,
            0x13: expiry,
            0x14: alice.identity.hash,
        }
        alice.invite_mgr._handle_join_request(fields, ch_hash)

        assert not alice.storage.is_member(ch_hash, bob.identity.hash_hex), \
            "Expired token was incorrectly accepted"

    def test_join_request_accepted_when_admin_identity_not_in_rns_recall(
        self, peer_factory
    ):
        """
        Regression: _verify_invite_token must not fail when the admin is the
        local node itself.

        RNS.Identity.recall() only returns identities learned from the network;
        it never returns the local identity.  Before this fix, an admin handling
        their own join request would get None from recall() and log
        "identity not known, path requested" — causing the invite to be silently
        dropped even though both peers were connected.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("self-admin-test", "", "invite")

        token, expiry = alice.invite_mgr.generate_invite_token(
            ch_hash, bob.identity.hash, ttl=3600
        )

        fields = {
            0x10: "join_request",
            0x01: bytes.fromhex(ch_hash),
            0x11: token,
            0x12: bob.identity.hash,
            0x13: expiry,
            0x14: alice.identity.hash,
        }

        # Patch RNS.Identity.recall to always return None, simulating a fresh
        # install where the local identity is not in the recall cache.
        # Use patch.object on the Identity class directly because RNS.Identity
        # may resolve to the module (not the class) depending on the RNS version,
        # which makes patch("RNS.Identity.recall") fail in that case.
        import RNS as _RNS
        _identity_cls = _RNS.Identity if isinstance(_RNS.Identity, type) else _RNS.Identity.Identity
        with patch.object(_identity_cls, "recall", return_value=None):
            alice.invite_mgr._handle_join_request(fields, ch_hash)

        assert alice.storage.is_member(ch_hash, bob.identity.hash_hex), \
            "Join request was rejected even though the admin is the local node"


class TestInviteFlow:
    def test_full_invite_flow(self, peer_factory):
        """
        Full end-to-end invite flow:
          1. Alice creates invite-only channel
          2. Alice sends invite to Bob
          3. Bob receives invite, sends join request back to Alice
          4. Alice verifies token, publishes updated member list
          5. Bob receives member list update and is now a member
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("private", "Invite only", "invite")

        def on_invite(channel_hash_hex, channel_name, token, expiry, admin_hex):
            bob.invite_mgr.send_join_request(channel_hash_hex, token, expiry, admin_hex)

        bob.invite_mgr.add_invite_callback(on_invite)

        alice.invite_mgr.send_invite(ch_hash, bob.identity.hash_hex)

        assert wait_for_member(alice.storage, ch_hash, bob.identity.hash_hex, timeout=5), \
            "Bob was not added to Alice's member list after join request"

        assert wait_for_member(bob.storage, ch_hash, bob.identity.hash_hex, timeout=5), \
            "Bob did not receive the member list update"

    def test_invite_callback_fires(self, peer_factory):
        """
        The invite_callback is fired when an MT_INVITE message is received.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("callback-invite", "", "invite")

        invites_received = []
        bob.invite_mgr.add_invite_callback(
            lambda ch, name, tok, exp, adm: invites_received.append(ch)
        )

        alice.invite_mgr.send_invite(ch_hash, bob.identity.hash_hex)

        assert wait_for(lambda: ch_hash in invites_received, timeout=5), \
            "Bob's invite callback was not fired"

    def test_channel_joined_callback_fires(self, peer_factory):
        """
        The channel_joined callback fires on Bob's side when he auto-joins
        via a member list update.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("joined-cb", "", "invite")

        joined = []
        bob.invite_mgr.add_channel_joined_callback(
            lambda ch, name: joined.append(ch)
        )

        def on_invite(channel_hash_hex, channel_name, token, expiry, admin_hex):
            bob.invite_mgr.send_join_request(channel_hash_hex, token, expiry, admin_hex)

        bob.invite_mgr.add_invite_callback(on_invite)
        alice.invite_mgr.send_invite(ch_hash, bob.identity.hash_hex)

        assert wait_for(lambda: ch_hash in joined, timeout=5), \
            "Bob's channel_joined callback was not fired"

    def test_non_member_message_dropped(self, peer_factory):
        """
        A message from a non-member to an invite-only channel is dropped.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")
        carol = peer_factory("carol")

        ch_hash = alice.channel_mgr.create_channel("members-only", "", "invite")

        # Bob is a member, Carol is not
        alice.storage.upsert_member(ch_hash, bob.identity.hash_hex, "Bob", False)
        bob.storage.upsert_channel(ch_hash, "members-only", "", alice.identity.hash_hex,
                                   "invite", time.time())
        bob.storage.subscribe(ch_hash)
        bob.storage.upsert_member(ch_hash, bob.identity.hash_hex, "Bob", False)
        bob.storage.upsert_member(ch_hash, alice.identity.hash_hex, "Alice", True)

        carol.storage.upsert_channel(ch_hash, "members-only", "", alice.identity.hash_hex,
                                     "invite", time.time())
        carol.storage.subscribe(ch_hash)

        carol.messaging.send_message(
            channel_hash_hex=ch_hash,
            content="I am not a member",
            subscriber_hashes=[alice.identity.hash_hex],
        )

        time.sleep(0.5)
        msgs = alice.storage.get_messages(ch_hash)
        assert len(msgs) == 0, "Alice accepted a message from a non-member Carol"


class TestMemberListVersioning:
    def test_higher_version_accepted(self, peer_factory):
        """
        A member list with a higher version number replaces the existing one.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("versioning", "", "invite")

        alice.invite_mgr.publish_member_list(ch_hash)
        v1 = alice.storage.get_member_list_version(ch_hash)
        assert v1["version"] == 1

        alice.invite_mgr.publish_member_list(ch_hash, add_members=[bob.identity.hash])
        v2 = alice.storage.get_member_list_version(ch_hash)
        assert v2["version"] == 2
        assert alice.storage.is_member(ch_hash, bob.identity.hash_hex)

    def test_lower_version_rejected(self, peer_factory):
        """
        A member list with a lower version than the current one is rejected.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")

        ch_hash = alice.channel_mgr.create_channel("reject-old", "", "invite")

        alice.invite_mgr.publish_member_list(ch_hash)
        alice.invite_mgr.publish_member_list(ch_hash, add_members=[bob.identity.hash])
        assert alice.storage.get_member_list_version(ch_hash)["version"] == 2

        ts = time.time()
        stale_doc = alice.invite_mgr._build_document(ch_hash, [alice.identity.hash],
                                                      [alice.identity.hash], 1, ts)
        accepted = alice.invite_mgr._accept_document(stale_doc, ch_hash)
        assert not accepted, "Stale v1 document was incorrectly accepted over v2"

    def test_member_list_broadcast_to_members(self, peer_factory):
        """
        When Alice publishes a member list, Bob (already a member) receives
        the updated list containing Carol.
        """
        alice = peer_factory("alice")
        bob = peer_factory("bob")
        carol = peer_factory("carol")

        ch_hash = alice.channel_mgr.create_channel("broadcast-ml", "", "invite")

        # Add Bob as a member
        alice.invite_mgr.publish_member_list(ch_hash, add_members=[bob.identity.hash])
        assert wait_for_member(alice.storage, ch_hash, bob.identity.hash_hex, timeout=5)

        # Set up Bob's storage so he can receive the member list
        bob.storage.upsert_channel(ch_hash, "broadcast-ml", "", alice.identity.hash_hex,
                                   "invite", time.time())
        bob.storage.subscribe(ch_hash)

        # Now add Carol — Bob should receive the updated list
        alice.invite_mgr.publish_member_list(ch_hash, add_members=[carol.identity.hash])

        assert wait_for_member(bob.storage, ch_hash, carol.identity.hash_hex, timeout=5), \
            "Bob did not receive the member list update containing Carol"
