; Inno Setup script for TrenchChat
;
; Produces a Windows installer (.exe) that:
;   - Installs to C:\Program Files\TrenchChat\ (or user-chosen dir)
;   - Upgrades in-place when the same AppId is detected
;   - Does NOT touch %USERPROFILE%\.trenchchat\ (user identity, DB, config)
;
; The wizard is themed to match the app: dark surfaces, phosphor-green text.
; Artwork in assets\ is generated by make_assets.py from the design tokens.
;
; Build from CI:
;   iscc /DAppVersion=%APP_VERSION% packaging\windows\trenchchat.iss

#define AppName "TrenchChat"
#define AppPublisher "TrenchChat"
#define AppURL "https://github.com/HunterL31/TrenchChat"
#define AppExeName "TrenchChat.exe"
#define AppTagline "Off-grid encrypted group chat over Reticulum."
; AppVersion is injected by CI via /DAppVersion=... on the iscc command line.
; Fallback for local builds:
#ifndef AppVersion
  #define AppVersion "0.1.0"
#endif

[Setup]
; Fixed GUID — Inno Setup uses this to detect an existing installation and
; perform an in-place upgrade rather than a side-by-side install.
; NEVER change this GUID once the first installer has been shipped.
AppId={{F3A2B1C0-9D4E-4F5A-8B6C-7E2D1A0F3B9C}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}/releases
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
; Allow per-user installs without admin rights
PrivilegesRequiredOverridesAllowed=dialog
; Output
OutputDir=..\..\dist\installer
OutputBaseFilename=TrenchChat-Setup-{#AppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
; Appearance
WizardStyle=modern
SetupIconFile=assets\trenchchat.ico
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName}
WizardImageFile=assets\wizard-large-100.bmp,assets\wizard-large-125.bmp,assets\wizard-large-150.bmp,assets\wizard-large-175.bmp,assets\wizard-large-200.bmp
WizardSmallImageFile=assets\wizard-small-100.bmp,assets\wizard-small-125.bmp,assets\wizard-small-150.bmp,assets\wizard-small-175.bmp,assets\wizard-small-200.bmp
DisableWelcomePage=no
DisableProgramGroupPage=yes
VersionInfoDescription={#AppName} Setup
VersionInfoProductName={#AppName}
VersionInfoCompany={#AppPublisher}
; Minimum Windows version: Windows 10
MinVersion=10.0
; Architecture
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
BeveledLabel={#AppName}
WelcomeLabel2=This will install [name/ver] on your computer.%n%n{#AppTagline} No servers, no accounts.%n%nClose any other applications before continuing.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The entire PyInstaller onedir output — all binaries, Qt libs, Python runtime
Source: "..\..\dist\TrenchChat\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove the installation directory on uninstall (app files only).
; The user data directory %USERPROFILE%\.trenchchat\ is intentionally
; NOT listed here — it is preserved across uninstalls and upgrades.
Type: filesandordirs; Name: "{app}"

[Code]
{ Wizard theming. Colours are the design tokens from
  flutter_ui/lib/theme/tokens.dart, written as Delphi's $00BBGGRR. }
const
  clSurface     = $00141712;  { ink-900 }
  clSurfaceHigh = $00191C17;  { ink-850 }
  clInset       = $0020241E;  { ink-800 }
  clTextBody    = $00D0D7D0;  { ink-200 }
  clTextHeading = $007DCA8C;  { green-200 }
  clTextMuted   = $00ABB2A9;  { ink-300 }

  DWMWA_USE_IMMERSIVE_DARK_MODE = 20;
  DWMWA_USE_IMMERSIVE_DARK_MODE_LEGACY = 19;

function DwmSetWindowAttribute(Wnd: HWND; Attribute: Integer; var Value: Integer;
  Size: Integer): Integer;
  external 'DwmSetWindowAttribute@dwmapi.dll stdcall delayload';

{ Windows paints the caption from the app's own light/dark preference, which a
  setup program never sets; without this the dark wizard wears a light frame. }
procedure UseDarkTitleBar(Wnd: HWND);
var
  Enable, Res: Integer;
begin
  Enable := 1;
  try
    Res := DwmSetWindowAttribute(Wnd, DWMWA_USE_IMMERSIVE_DARK_MODE, Enable, 4);
    if Res <> 0 then
      Res := DwmSetWindowAttribute(Wnd, DWMWA_USE_IMMERSIVE_DARK_MODE_LEGACY, Enable, 4);
  except
  end;
end;

procedure DarkenControls(Parent: TWinControl);
var
  I: Integer;
  Child: TControl;
begin
  for I := 0 to Parent.ControlCount - 1 do
  begin
    Child := Parent.Controls[I];

    if Child is TBevel then
      TBevel(Child).Visible := False
    else if Child is TNewStaticText then
      TNewStaticText(Child).Font.Color := clTextBody
    else if Child is TNewNotebookPage then
      TNewNotebookPage(Child).Color := clSurface
    else if Child is TPanel then
      TPanel(Child).Color := clSurfaceHigh
    else if Child is TBitmapImage then
      TBitmapImage(Child).BackColor := clSurfaceHigh
    else if Child is TEdit then
    begin
      TEdit(Child).Color := clInset;
      TEdit(Child).Font.Color := clTextBody;
    end
    else if Child is TMemo then
    begin
      TMemo(Child).Color := clInset;
      TMemo(Child).Font.Color := clTextBody;
    end
    else if Child is TNewCheckListBox then
    begin
      TNewCheckListBox(Child).Color := clSurface;
      TNewCheckListBox(Child).Font.Color := clTextBody;
    end;

    if Child is TWinControl then
      DarkenControls(TWinControl(Child));
  end;
end;

procedure InitializeWizard();
begin
  WizardForm.Color := clSurface;
  DarkenControls(WizardForm);
  WizardForm.MainPanel.Color := clSurfaceHigh;
  WizardForm.PageNameLabel.Font.Color := clTextHeading;
  WizardForm.WelcomeLabel1.Font.Color := clTextHeading;
  WizardForm.FinishedHeadingLabel.Font.Color := clTextHeading;
  WizardForm.PageDescriptionLabel.Font.Color := clTextMuted;
  WizardForm.DiskSpaceLabel.Font.Color := clTextMuted;
  WizardForm.FilenameLabel.Font.Color := clTextMuted;
  UseDarkTitleBar(WizardForm.Handle);
end;

procedure InitializeUninstallProgressForm();
begin
  UninstallProgressForm.Color := clSurface;
  DarkenControls(UninstallProgressForm);
  UninstallProgressForm.MainPanel.Color := clSurfaceHigh;
  UninstallProgressForm.PageNameLabel.Font.Color := clTextHeading;
  UninstallProgressForm.PageDescriptionLabel.Font.Color := clTextMuted;
  UninstallProgressForm.StatusLabel.Font.Color := clTextMuted;
  UseDarkTitleBar(UninstallProgressForm.Handle);
end;
